---

- name: Blue Green Deploy
  hosts: "{{ blue_green_color }}"
  become: yes

  vars:
    source_file: /home/ubuntu/lesson4/my-app
    destin_file: /home/ubuntu

  tasks:
  - name: Copy file to servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=755
    notify: Restart Apache

  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted


- name: Switcher configurator
  hosts: proxy
  become: yes

  tasks:
  - name: Generate configure file to HAProxy
    template: >
      src="./haproxy.j2"
      dest=/etc/haproxy/haproxy.cfg
  handlers:
  - name: Restart Proxy
    service: name=haproxy state=restarted

